<a href="https://colab.research.google.com/github/Krishan-Kumar-kk/Classification_problems_-ml/blob/main/credit_fraud_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import pandas as pd
import numpy as numpy 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [113]:
df=pd.read_csv("creditcard.csv")
test=pd.read_csv('test.csv')

In [114]:
testdf

          ID    Time        V1        V2  ...       V26       V27       V28  Amount
0     198366  132459  2.079192  0.052662  ...  0.179993 -0.072265 -0.034296    0.99
1     198367  132460  1.596563 -1.588177  ... -0.055686  0.033064 -0.042575  183.02
2     198368  132460  2.273454 -1.447207  ... -0.148293  0.020379 -0.063042   21.00
3     198369  132460  1.987406  0.140840  ... -0.473680 -0.045832 -0.075119   35.00
4     198370  132461 -0.398751  1.370313  ... -0.222038  0.657472  0.278362    0.89
...      ...     ...       ...       ...  ...       ...       ...       ...     ...
8553  206919  136440 -0.895783  0.442373  ...  1.241821 -0.149762  0.059280  119.00
8554  206920  136441 -0.806650  1.319676  ... -0.189494  0.388007  0.246438    4.29
8555  206921  136442 -0.696534  2.256872  ...  0.429330  0.332805  0.269920    1.00
8556  206922  136443 -0.370045 -0.865379  ... -0.180881  0.122947  0.143287   10.00
8557  206923  136443  2.063096 -0.956815  ... -0.077652 -0.075792 -0.063865   81.00

[8558 rows x 31 columns]

In [115]:
testdf=test.copy()

testdf.dropna(inplace=True)

In [116]:
testy=testdf.drop(['ID'],axis=1)
testy

         Time         V1         V2  ...       V27       V28  Amount
0      132459   2.079192   0.052662  ... -0.072265 -0.034296    0.99
1      132460   1.596563  -1.588177  ...  0.033064 -0.042575  183.02
2      132460   2.273454  -1.447207  ...  0.020379 -0.063042   21.00
3      132460   1.987406   0.140840  ... -0.045832 -0.075119   35.00
4      132461  -0.398751   1.370313  ...  0.657472  0.278362    0.89
...       ...        ...        ...  ...       ...       ...     ...
86437  172786 -11.881118  10.071785  ...  0.943651  0.823731    0.77
86438  172787  -0.732789  -0.055080  ...  0.068472 -0.053527   24.79
86439  172788   1.919565  -0.301254  ...  0.004455 -0.026561   67.88
86440  172788  -0.240440   0.530483  ...  0.108821  0.104533   10.00
86441  172792  -0.533413  -0.189733  ... -0.002415  0.013649  217.00

[86442 rows x 30 columns]

In [117]:
testdf.isnull().sum()

ID        0
Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
dtype: int64

In [118]:
df

            Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]

In [119]:
df.drop('Time',axis=1 )

               V1         V2        V3  ...       V28  Amount  Class
0       -1.359807  -0.072781  2.536347  ... -0.021053  149.62      0
1        1.191857   0.266151  0.166480  ...  0.014724    2.69      0
2       -1.358354  -1.340163  1.773209  ... -0.059752  378.66      0
3       -0.966272  -0.185226  1.792993  ...  0.061458  123.50      0
4       -1.158233   0.877737  1.548718  ...  0.215153   69.99      0
...           ...        ...       ...  ...       ...     ...    ...
284802 -11.881118  10.071785 -9.834783  ...  0.823731    0.77      0
284803  -0.732789  -0.055080  2.035030  ... -0.053527   24.79      0
284804   1.919565  -0.301254 -3.249640  ... -0.026561   67.88      0
284805  -0.240440   0.530483  0.702510  ...  0.104533   10.00      0
284806  -0.533413  -0.189733  0.703337  ...  0.013649  217.00      0

[284807 rows x 30 columns]

# EDA

In [120]:
df.Class.unique()

array([0, 1])

In [121]:
df['Class'].mode()

0    0
dtype: int64

In [122]:
df['Class'].fillna(df['Class'].mode()[0],inplace=True)

In [123]:
df.Class.unique()

array([0, 1])

In [124]:
Fraud_case=df[df.Class == 1]
Fraud_case

            Time        V1        V2  ...       V28  Amount  Class
541        406.0 -2.312227  1.951992  ... -0.143276    0.00      1
623        472.0 -3.043541 -3.157307  ...  0.035764  529.00      1
4920      4462.0 -2.303350  1.759247  ... -0.153029  239.93      1
6108      6986.0 -4.397974  1.358367  ...  0.849573   59.00      1
6329      7519.0  1.234235  3.019740  ...  0.146793    1.00      1
...          ...       ...       ...  ...       ...     ...    ...
279863  169142.0 -1.927883  1.125653  ...  0.147968  390.00      1
280143  169347.0  1.378559  1.289381  ...  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366  ...  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864  ... -0.253700  245.00      1
281674  170348.0  1.991976  0.158476  ... -0.015309   42.53      1

[492 rows x 31 columns]

In [125]:
non_Fraud_case=df[df.Class == 0]
non_Fraud_case

            Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284315 rows x 31 columns]

In [126]:
print('total_Fraud_cases',len(Fraud_case))
print('total_non_Fraud_cases',len(non_Fraud_case))

total_Fraud_cases 492
total_non_Fraud_cases 284315

In [127]:
fraud_percentage=(len(Fraud_case)/len(df['Class']))*100
print("fraud_percentage:",fraud_percentage)

fraud_percentage: 0.1727485630620034

In [128]:
non_fraud_percentage=(len(non_Fraud_case)/len(df['Class']))*100
print("non_fraud_percentage:",non_fraud_percentage)

non_fraud_percentage: 99.82725143693798

In [129]:
from sklearn.preprocessing import StandardScaler

In [130]:
sc = StandardScaler()

In [131]:
amount = df['Amount'].values

df['Amount'] = sc.fit_transform(amount.reshape(-1, 1))

In [132]:
df['Amount'].head(10)

0    0.244964
1   -0.342475
2    1.160686
3    0.140534
4   -0.073403
5   -0.338556
6   -0.333279
7   -0.190107
8    0.019392
9   -0.338516
Name: Amount, dtype: float64



# TEST AND TRAIN SPLIT

In [133]:
from sklearn.model_selection import train_test_split

In [134]:
X = df.drop('Class', axis = 1).values
y= df['Class'].values

In [135]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [136]:
X_train.shape

(227845, 30)

In [137]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

# MODEL

In [138]:
#1. DecisionTreeClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix # evaluation metric
from sklearn.metrics import accuracy_score # evaluation metric
from sklearn.metrics import f1_score # evaluation metric

In [139]:
tree_model = DecisionTreeClassifier(max_depth = 4, criterion = 'entropy')

In [140]:
tree_model.fit(X_train, y_train)
tree_yhat = tree_model.predict(X_test)

In [141]:
accuracy_score(y_test, tree_yhat)

0.9993679997191109

In [142]:
f1_score(y_test, tree_yhat)

0.8105263157894738

In [143]:
#2 KNeighborsClassifier

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [144]:
n=5
knn = KNeighborsClassifier(n_neighbors = n)
knn.fit(X_train, y_train)
knn_yhat = knn.predict(X_test)

In [145]:
accuracy_score(y_test, knn_yhat)

0.9983848881710614

In [146]:
from sklearn.linear_model import LogisticRegression # Logistic regression algorithm
from sklearn.svm import SVC # SVM algorithm
from sklearn.ensemble import RandomForestClassifier # Random forest tree algorithm
from xgboost import XGBClassifier # XGBoost algorithm

In [147]:
# 3. Logistic Regression

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_yhat = lr.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [148]:
# 4. SVM 

svm = SVC()
svm.fit(X_train, y_train)
svm_yhat = svm.predict(X_test)
f1_score(y_test,svm_yhat)

0.0

In [149]:
# 5. Random Forest Tree

rf = RandomForestClassifier(max_depth = 4)
rf.fit(X_train, y_train)
rf_yhat = rf.predict(X_test)

In [150]:
# 6. XGBoost

xgb = XGBClassifier(max_depth = 4)
xgb.fit(X_train, y_train)
xgb_yhat = xgb.predict(X_test)

In [151]:
print("Compare accuracy score:")
print("accuracy_score of  DecisionTree: ",accuracy_score(y_test, tree_yhat))
print("------------------------------------------------------------------------")
print("accuracy_score of  KNeighborsClassifier: ",accuracy_score(y_test, knn_yhat))
print("------------------------------------------------------------------------")
print("accuracy_score of  Logistic Regression: ",accuracy_score(y_test,lr_yhat))
print("------------------------------------------------------------------------")
print("accuracy_score of  Random Forest Tree: ",accuracy_score(y_test, rf_yhat))
print("------------------------------------------------------------------------")
print("accuracy_score of  XGBoost: ",accuracy_score(y_test, xgb_yhat))
print("------------------------------------------------------------------------")
print("accuracy_score of   SVM: ",accuracy_score(y_test, svm_yhat))

Compare accuracy score:
accuracy_score of  DecisionTree:  0.9993679997191109
------------------------------------------------------------------------
accuracy_score of  KNeighborsClassifier:  0.9983848881710614
------------------------------------------------------------------------
accuracy_score of  Logistic Regression:  0.9990168884519505
------------------------------------------------------------------------
accuracy_score of  Random Forest Tree:  0.9992977774656788
------------------------------------------------------------------------
accuracy_score of  XGBoost:  0.9994733330992591
------------------------------------------------------------------------
accuracy_score of   SVM:  0.9982268881008391

In [152]:
print("Compare F1 Score:")
print("f1_score of  DecisionTree: ",f1_score(y_test, tree_yhat))
print("------------------------------------------------------------------------")
print("f1_score of  KNeighborsClassifier: ",f1_score(y_test, knn_yhat))
print("------------------------------------------------------------------------")
print("f1_score of  Logistic Regression: ",f1_score(y_test,lr_yhat))
print("------------------------------------------------------------------------")
print("f1_score of  Random Forest Tree: ",f1_score(y_test, rf_yhat))
print("------------------------------------------------------------------------")
print("f1_score of  XGBoost: ",f1_score(y_test, xgb_yhat))
print("------------------------------------------------------------------------")
print("f1_score of   SVM: ",f1_score(y_test, svm_yhat))

Compare F1 Score:
f1_score of  DecisionTree:  0.8105263157894738
------------------------------------------------------------------------
f1_score of  KNeighborsClassifier:  0.1636363636363636
------------------------------------------------------------------------
f1_score of  Logistic Regression:  0.7333333333333334
------------------------------------------------------------------------
f1_score of  Random Forest Tree:  0.7727272727272727
------------------------------------------------------------------------
f1_score of  XGBoost:  0.8421052631578948
------------------------------------------------------------------------
f1_score of   SVM:  0.0

In [153]:
class_pred = rf.predict(testy)
testy['pred_class']=class_pred

In [154]:
testy

         Time         V1         V2  ...       V28  Amount  pred_class
0      132459   2.079192   0.052662  ... -0.034296    0.99           0
1      132460   1.596563  -1.588177  ... -0.042575  183.02           0
2      132460   2.273454  -1.447207  ... -0.063042   21.00           0
3      132460   1.987406   0.140840  ... -0.075119   35.00           0
4      132461  -0.398751   1.370313  ...  0.278362    0.89           0
...       ...        ...        ...  ...       ...     ...         ...
86437  172786 -11.881118  10.071785  ...  0.823731    0.77           0
86438  172787  -0.732789  -0.055080  ... -0.053527   24.79           0
86439  172788   1.919565  -0.301254  ... -0.026561   67.88           0
86440  172788  -0.240440   0.530483  ...  0.104533   10.00           0
86441  172792  -0.533413  -0.189733  ...  0.013649  217.00           0

[86442 rows x 31 columns]

In [158]:
testy.pred_class.unique()

array([0, 1])

**predicted result**

In [155]:
pd.DataFrame(testy).to_excel('credit_fraud_prediction.xlsx')